name: Alert the team of upstream changes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'
  
jobs:
  check-for-updates:
    name: Check for updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: | # shell
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config pull.rebase false

      - name: Add upstream
        run: | # shell
          git remote add upstream https://github.com/actions/runner.git
          git fetch upstream

      - name: Checkout upstream as temporary branch
        run: | # shell
          if [[ $(git rev-parse --verify origin/upstream-main) ]]
          then
            git checkout --track origin/upstream-main
            git rebase main
            git checkout --theirs .
          else
            git checkout -b upstream-main
          fi
          git pull upstream main

      - name: Open PR
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | # shell
          getPRNumber() {
            gh pr list \
              --repo ${{ github.repository }} \
              --json number \
              --head upstream-main \
            | jq '.[0].number'
          }

          if [[ $(git rev-list --count main..upstream-main) > 0 ]]
          then
            git push --force origin upstream-main

            last_pr_id=$( getPRNumber )

            if [[ $last_pr_id == 'null' ]]
            then
              gh pr create \
                --repo ${{ github.repository }} \
                --base main \
                --body "There are changes in the upstream repository that you should release. Once merged, please run the [publish-image workflow](https://github.com/${{ github.repository }}/actions/workflows/publish-image.yml)". \
                --head upstream-main \
                --title "Pulling upstream changes"

              echo "id=$( getPRNumber )" >> $GITHUB_OUTPUT
            else
              echo "id=${last_pr_id}" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Slack Notification
        if: steps.pr.outputs.id != ''
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':octocat:'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: <@ads-team> There are changes in the upstream repository that you should add to your Arc Runner. <https://github.com/${{ github.repository }}/pull/${{ steps.pr.outputs.id }}|View the PR>
          SLACK_USERNAME: GitHub Arc
